server:
  port: 8002
spring:
  application:
    name: servicio-item
servicio-productos:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8001,localhost:9001
    ServerListRefreshInterval: 15000